### PR TITLE
APP-23 Publish to GH Packages

### PR DESCRIPTION
**Pull request by eduardbosch-jt**
### :tophat: What is the goal?

Publish lib to GH Packages so we can remove AWS from the Workers app

### How is it being implemented?

- Migrate to vanniktech maven plugin.
- Define GH Package repository.

### Captures, GIF or Videos (UI Tasks)

Screenshot 2024-05-28 at 15 13 11

### CODE REVIEW

**Review by douglaspanacho-jt — APPROVED** [review]
Thanks for handling this Edu! 🥇

**Review by diego-francisco-jt — APPROVED** [review]
Good job, Edu! ❤️ 
This was on my to-do list but you know, really hard to have time to do it so glad that you're in the core team now 🙌

**Review by khelben5 — APPROVED** [review]
LGTM

**Comment by eduardbosch-jt** [comment]
> LGTM

Haha, thanks Eduardo for still helping J&T to review PRs. Much appreciated 😆 🔝

**Pull request merged**
